version: "3.9"
services:
  app:
    build:
      context: ./files
      dockerfile: ../Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./files:/files
    command: julia -e 'using Pluto; Pluto.run(host="0.0.0.0", port=8000, require_secret_for_open_links=false, require_secret_for_access=false)'
